name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew clean build

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: jar-file
        path: build/libs/demo-0.0.1-SNAPSHOT.jar

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Download artifact
      uses: actions/download-artifact@v2
      with:
        name: jar-file

    - name: Copy JAR to EC2
      env:
        AWS_REGION: ${{ secrets.AWS_REGION }}
        EC2_USER: ${{ secrets.EC2_USER }}
        EC2_HOST: ${{ secrets.EC2_HOST }}
        EC2_KEY: ${{ secrets.EC2_KEY }}
      run: |
        scp -i $EC2_KEY demo-0.0.1-SNAPSHOT.jar $EC2_USER@$EC2_HOST:/home/ec2-user/demo-0.0.1-SNAPSHOT.jar

    - name: SSH and Run JAR
      env:
        EC2_USER: ${{ secrets.EC2_USER }}
        EC2_HOST: ${{ secrets.EC2_HOST }}
        EC2_KEY: ${{ secrets.EC2_KEY }}
      run: |
        ssh -i $EC2_KEY $EC2_USER@$EC2_HOST << 'EOF'
          nohup java -jar /home/ec2-user/demo-0.0.1-SNAPSHOT.jar > /home/ec2-user/demo.log 2>&1 &
        EOF
